version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:0806@localhost/dbname

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
